# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'municipios_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'municipios_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  municipios_analytics:
    # Config indicated by + and target files apply to all files under models/
    +materialized: view

    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'bronze']

    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate', 'silver']

    marts:
      +materialized: table
      +schema: marts
      dimensions:
        +tags: ['dimension', 'gold']
      facts:
        +tags: ['fact', 'gold']

# Seed configurations
seeds:
  municipios_analytics:
    +schema: seeds

# Variables
vars:
  # Default year for analyses
  analysis_year: 2010
  # Latest available year for population data
  latest_population_year: 2022
  # Latest available year for electoral data
  latest_election_year: 2024
